# Meta
description: Private theme for nartifact
keywords: hexo,theme,artifact,otakism

# Author
author_avatar: /img/avatar.png

# Search
search: 
  enable: true
  service: algolia # google/algolia/azure
  # google 
  google_api_key: googleApiKey
  google_engine_id: googleEngineId
  # algolia
  algolia_app_id: 6V5SMRF05M
  algolia_api_key: 2b2a71475f57312c7a1281ca8e83c117
  algolia_index_name: nartifact
  # azure
  azure_service_name: 
  azure_index_name: 
  azure_query_key: 

# Miscellaneous
google_analytics: trackingID
baidu_sitemap: baiduSitemapID
baidu_analytics: baiduTrackingID
favicon: /favicon.png

# Less
less:
  compress: true

# Comment
disqus_shortname:
valine:
  enable: false
  appid:
  appkey:
  notify: false
  verify: false
  placeholder: Just go go
  avatar: retro
  guest_info: nick,mail,link
  pageSize: 10
  visitor: false

# use url, not username
social:
- name: feed
  url: /atom.xml
- name: mail
  url: mailto:remarkable.yh@outlook.com
- name: github
  url: https://github.com/nartifact
- name: twitter
  url: 
- name: google
  url: 
- name: facebook
  url: 
- name: linkedin
  url: 
- name: weibo
  url: 
- name: tumblr
  url: 
- name: dribbble
  url: 
- name: pinterest
  url: 
- name: instagram
  url: 
- name: behance
  url: 
